server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://10.10.5.104:3306/zy_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 123456
  redis:
    host: 10.10.5.104
    port: 6379