spring:
  profiles:
    active: dev
  main:
    # 允许BeanDefinition出现重复名称，子类可以覆盖
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    # 关闭驼峰到下划线的映射
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 关闭数据库表的下划线映射
      table-underline: false
  # 枚举映射包
  typeEnumsPackage: cn.cuilan.ssmp.enums

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  row-bounds-with-count: true