# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# 工作流程的名称
name: Maven Package

#  触发工作流程的 GitHub 事件的名称
on:
  push:
    branches:
      - master
#  pull_request:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B -DskipTests=true package --file pom.xml
